version:                        '2'
services:
  phpback:
  db:
    image:                      mysql:5.6
    command:                    --default-authentication-plugin=mysql_native_password
    restart:                    on-failure
    environment:
      MYSQL_ROOT_PASSWORD:      my-secret-pw
      MYSQL_USER:               phpback
      MYSQL_PASSWORD:           phpbackpwd
      MYSQL_DATABASE:           phpbackdb
    ports:
      - 3306:3306
  phpback:
    depends_on:
      - db
    image:                      scretu/phpback:latest
    restart:                    on-failure
    environment:
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_USER:               phpback
      MYSQL_PASSWORD:           phpbackpwd
      MYSQL_NAME:               phpbackdb
      APP_TITLE:                'My Application Feedback'
      APP_ADMIN_EMAIL:          'x@x.x'
      APP_ADMIN_PWD:            'complic8ed'
      APP_CAPTCHA_PUBLIC:       'huh'
      APP_CAPTCHA_PRIVATE:      'same'
      APP_SMTP_HOST:            'localhost'
      APP_SMTP_USER:            'user'
      APP_SMTP_PWD:             'password'
      APP_SMTP_PORT:            25
    ports:
      - 80:80
